version: '2'

services:

  track:
    build: comp_tracking/
    networks:
      - konipynet

  visual:
    build: comp_visualising/
    restart: unless-stopped
    networks:
      - konipynet
    ports:
      - "8989:8989"


networks:
  konipynet:
    driver: bridge
